// This is autogenerated code - 12:11 PM 1/28/2016

#ifndef OSGENERAL_H
#define OSGENERAL_H

#include "OSGeneralApi.h"
#include <xOSa/xOSaClientApi.h>

#ifdef __cplusplus
extern "C" {
#endif

#if defined(XOSA_WINDOWS) && defined(XOSA_PLUGIN_OSGENERAL_EXPORTS)
	#define XOSA_PLUGIN_OSGeneral_API __declspec(dllexport)
#elif defined(XOSA_WINDOWS) && !defined(XOSA_PLUGIN_OSGENERAL_EXPORTS)
	#define XOSA_PLUGIN_OSGeneral_API __declspec(dllimport)
#else
	#define XOSA_PLUGIN_OSGeneral_API 
#endif


XOSA_PLUGIN_OSGeneral_API XOSA_STATUS __cdecl XOSA_PLUGIN_OSGeneralSetAutoRotate (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	bool enable, OSGENERAL_STATUS*  returnValue);
XOSA_PLUGIN_OSGeneral_API XOSA_STATUS __cdecl XOSA_PLUGIN_OSGeneralDoQuery (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	uint32_t bufsize, char* buf, uint32_t* reqsize, char* objName, char* objPath, char* prop, char* iface, OSGENERAL_STATUS*  returnValue);

XOSA_PLUGIN_OSGeneral_API XOSA_STATUS __cdecl XOSA_PLUGIN_OSGeneralGetOrientation(struct XosaClientConnection * conn, 
	const struct XosaClientApiCallParameters *params, uint32_t* orientation, OSGENERAL_STATUS*  returnValue);

XOSA_PLUGIN_OSGeneral_API XOSA_STATUS __cdecl XOSA_PLUGIN_OSGeneralSetOrientation(struct XosaClientConnection * conn,
	const struct XosaClientApiCallParameters *params, uint32_t orientation, OSGENERAL_STATUS*  returnValue);

#ifdef __cplusplus
}
#endif

#endif