// This is autogenerated code - 16:31 9/1/2015

#ifndef UIAUTOMATION_H
#define UIAUTOMATION_H

#include "UIAutomationApi.h"
#include <xOSa/xOSaClientApi.h>

#ifdef __cplusplus
extern "C" {
#endif

#if defined(XOSA_WINDOWS) && defined(UIAutomation_EXPORTS)
	#define XOSA_PLUGIN_UIAutomation_API __declspec(dllexport)
#elif defined(XOSA_WINDOWS) && !defined(UIAutomation_EXPORTS)
	#define XOSA_PLUGIN_UIAutomation_API __declspec(dllimport)
#else
	#define XOSA_PLUGIN_UIAutomation_API 
#endif


XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_CallPattern (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *parms,
	AutomationElementHandle handle, int id, wchar_t* method, wchar_t* signature, wchar_t* params, uint32_t size, wchar_t* result, uint32_t* req_size, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_GetText (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	AutomationElementHandle handle, uint32_t text_size, wchar_t* text, uint32_t* required_size, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_GetPropertyValue (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	AutomationElementHandle handle, int32_t property_id, uint32_t text_size, wchar_t* text, uint32_t* required_size, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_SetFocus (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	void* hwnd, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_Find (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	UIA_FindType type, AutomationElementHandle start_handle, SearchParameters* sp, int32_t n_handles, AutomationElementHandle* handles, int32_t* n_handles_required, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_GetState (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	AutomationElementHandle handle, UIA_StatePattern pattern, int32_t* result, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_MouseClick (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	int x, int y, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_ToastClick (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_SendKey (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	int code, bool up, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_GetParent (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	AutomationElementHandle handle, AutomationElementHandle* parent, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_SetText (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	AutomationElementHandle handle, wchar_t* text, uint32_t text_size, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_ClickButtonOnWindow (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* wndname, char* btnname, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_Release (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	AutomationElementHandle handle, UIAUTOMATION_STATUS*  returnValue);
XOSA_PLUGIN_UIAutomation_API XOSA_STATUS __cdecl XOSA_PLUGIN_UIAutomationUIAutomation_Invoke (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	AutomationElementHandle handle, UIA_InvokePattern pattern, UIAUTOMATION_STATUS*  returnValue);

#ifdef __cplusplus
}
#endif

#endif