// This is autogenerated code - 14:09 8/25/2016

#ifndef DEVCON_H
#define DEVCON_H

#include "DevconApi.h"
#include <xOSa/xOSaClientApi.h>

#ifdef __cplusplus
extern "C" {
#endif

#if defined(XOSA_WINDOWS) && defined(Devcon_EXPORTS)
	#define XOSA_PLUGIN_Devcon_API __declspec(dllexport)
#elif defined(XOSA_WINDOWS) && !defined(Devcon_EXPORTS)
	#define XOSA_PLUGIN_Devcon_API __declspec(dllimport)
#else
	#define XOSA_PLUGIN_Devcon_API 
#endif


XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconGetDriverFiles (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, uint32_t size, StringData* files, uint32_t* required_size, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconAddDP (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* inf, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconUpdateDriverNI (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* inf, char* device, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconDisableDevice (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconGetStatus (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, uint32_t size, StatusData* statuses, uint32_t* required_size, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconFind (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, uint32_t size, StringData* devices, uint32_t* required_size, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconGetDriverNodes (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, uint32_t size, DriverNode* swarray, uint32_t* required_size, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconInstallDriver (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* inf, char* device, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconFindAll (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, uint32_t size, StringData* devices, uint32_t* required_size, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconGetStatusEx (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, uint32_t size, StatusDataEx* statuses, uint32_t* required_size, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconGetDevconError (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	uint32_t size, char* errorMsg, uint32_t* errorCode, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconRemoveDriver (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* device, bool deleteDP, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconRescan (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconUpdateDriver (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* inf, char* device, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconGetDriverResources (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, uint32_t size, DriverResources* swarray, uint32_t* required_size, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconEnableDevice (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconGetDeviceHwids (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, uint32_t size, StringData* ids, uint32_t* required_size, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconRestartDevice (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconRemoveDP (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* inf, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconGetClassDevices (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, uint32_t size, StringData* devices, uint32_t* required_size, DEVCON_STATUS*  returnValue);
XOSA_PLUGIN_Devcon_API XOSA_STATUS __cdecl XOSA_PLUGIN_DevconGetAllClasses (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	uint32_t size, StringData* classes, uint32_t* required_size, DEVCON_STATUS*  returnValue);

#ifdef __cplusplus
}
#endif

#endif