// This is autogenerated code - 14:30 4/28/2015

#ifndef P2P_H
#define P2P_H

#include "P2PApi.h"
#include <xOSa/xOSaClientApi.h>

#ifdef __cplusplus
extern "C" {
#endif

#if defined(XOSA_WINDOWS) && defined(P2P_EXPORTS)
	#define XOSA_PLUGIN_P2P_API __declspec(dllexport)
#elif defined(XOSA_WINDOWS) && !defined(P2P_EXPORTS)
	#define XOSA_PLUGIN_P2P_API __declspec(dllimport)
#else
	#define XOSA_PLUGIN_P2P_API 
#endif


XOSA_PLUGIN_P2P_API XOSA_STATUS __cdecl XOSA_PLUGIN_P2PPing (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, char* sourceip, bool tbt, uint32_t packet_size, uint32_t packets, uint32_t* lost, uint32_t* time, P2P_STATUS*  returnValue);
XOSA_PLUGIN_P2P_API XOSA_STATUS __cdecl XOSA_PLUGIN_P2PFileTransfer (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	bool receive, uint32_t port, char* dest, char* filename, bool udp, uint32_t* Bps, P2P_STATUS*  returnValue);
XOSA_PLUGIN_P2P_API XOSA_STATUS __cdecl XOSA_PLUGIN_P2PSetIPConfig (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, char* ipaddress, char* netmask, char* gw, bool dhcp, bool tbt, P2P_STATUS*  returnValue);
XOSA_PLUGIN_P2P_API XOSA_STATUS __cdecl XOSA_PLUGIN_P2PGetRemoteIP (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, char* ip4addr, char* ip6addr, bool tbt, P2P_STATUS*  returnValue);
XOSA_PLUGIN_P2P_API XOSA_STATUS __cdecl XOSA_PLUGIN_P2PGetIPConfig (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* name, IPINFO* info, uint32_t descsize, char* desc, bool tbt, P2P_STATUS*  returnValue);

#ifdef __cplusplus
}
#endif

#endif