// This is autogenerated code - 12:28 1/13/2015

#ifndef TBTSIM_H
#define TBTSIM_H

#include "TbtSimApi.h"
#include <xOSa/xOSaClientApi.h>

#ifdef __cplusplus
extern "C" {
#endif

#if defined(XOSA_WINDOWS) && defined(TbtSim_EXPORTS)
	#define XOSA_PLUGIN_TbtSim_API __declspec(dllexport)
#elif defined(XOSA_WINDOWS) && !defined(TbtSim_EXPORTS)
	#define XOSA_PLUGIN_TbtSim_API __declspec(dllimport)
#else
	#define XOSA_PLUGIN_TbtSim_API 
#endif


XOSA_PLUGIN_TbtSim_API XOSA_STATUS __cdecl XOSA_PLUGIN_TbtSimPerformCall (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* indata, uint32_t out_size, char* outdata, TBTSIM_STATUS*  returnValue);

#ifdef __cplusplus
}
#endif

#endif