// This is autogenerated code - 4:17 PM 2/25/2015

#ifndef NETREMOTING_H
#define NETREMOTING_H

#include "NetRemoting.h"
#include <xOSa/xOSaClientApi.h>

#ifdef __cplusplus
extern "C" {
#endif

#if defined(XOSA_WINDOWS) && defined(NetRemoting_EXPORTS)
	#define XOSA_PLUGIN_NetRemoting_API __declspec(dllexport)
#elif defined(XOSA_WINDOWS) && !defined(NetRemoting_EXPORTS)
	#define XOSA_PLUGIN_NetRemoting_API __declspec(dllimport)
#else
	#define XOSA_PLUGIN_NetRemoting_API 
#endif


XOSA_PLUGIN_NetRemoting_API XOSA_STATUS __cdecl XOSA_PLUGIN_NetRemotingStartServer (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	unsigned int port, NET_REMOTING_STATUS*  returnValue);
XOSA_PLUGIN_NetRemoting_API XOSA_STATUS __cdecl XOSA_PLUGIN_NetRemotingRegisterServiceTypes (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* dllOrDirectoryPath, NET_REMOTING_STATUS*  returnValue);
XOSA_PLUGIN_NetRemoting_API XOSA_STATUS __cdecl XOSA_PLUGIN_NetRemotingStopServer (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	unsigned int port, NET_REMOTING_STATUS*  returnValue);
XOSA_PLUGIN_NetRemoting_API XOSA_STATUS __cdecl XOSA_PLUGIN_NetRemotingSetCurrentDirectory(
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char *currentDirectory, NET_REMOTING_STATUS*  returnValue);

#ifdef __cplusplus
}
#endif

#endif