// This is autogenerated code - 17:52 1/12/2015

#ifndef TENLIRA_H
#define TENLIRA_H

#include "TenLiraApi.h"
#include <xOSa/xOSaClientApi.h>

#ifdef __cplusplus
extern "C" {
#endif

#if defined(XOSA_WINDOWS) && defined(TenLira_EXPORTS)
	#define XOSA_PLUGIN_TenLira_API __declspec(dllexport)
#elif defined(XOSA_WINDOWS) && !defined(TenLira_EXPORTS)
	#define XOSA_PLUGIN_TenLira_API __declspec(dllimport)
#else
	#define XOSA_PLUGIN_TenLira_API 
#endif


XOSA_PLUGIN_TenLira_API XOSA_STATUS __cdecl XOSA_PLUGIN_TenLiraGetLibraryVersion (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	uint32_t text_size, char* text, uint32_t* required_size, TENLIRA_STATUS*  returnValue);
XOSA_PLUGIN_TenLira_API XOSA_STATUS __cdecl XOSA_PLUGIN_TenLiraWriteEEPROMByte (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* route_string, uint8_t offset, uint8_t value, uint8_t mask, TENLIRA_STATUS*  returnValue);
XOSA_PLUGIN_TenLira_API XOSA_STATUS __cdecl XOSA_PLUGIN_TenLiraWriteFlashByte (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* route_string, uint8_t offset, uint8_t value, uint8_t mask, TENLIRA_STATUS*  returnValue);
XOSA_PLUGIN_TenLira_API XOSA_STATUS __cdecl XOSA_PLUGIN_TenLiraGetTenliraErrorText (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	uint32_t text_size, char* text, uint32_t* required_size, TENLIRA_STATUS*  returnValue);
XOSA_PLUGIN_TenLira_API XOSA_STATUS __cdecl XOSA_PLUGIN_TenLiraReadEEPROMByte (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* route_string, uint8_t offset, uint8_t* value, TENLIRA_STATUS*  returnValue);
XOSA_PLUGIN_TenLira_API XOSA_STATUS __cdecl XOSA_PLUGIN_TenLiraGetSwitches (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	uint32_t size, Switch* swarray, uint32_t* required_size, TENLIRA_STATUS*  returnValue);
XOSA_PLUGIN_TenLira_API XOSA_STATUS __cdecl XOSA_PLUGIN_TenLiraRefreshDevices (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	TENLIRA_STATUS*  returnValue);
XOSA_PLUGIN_TenLira_API XOSA_STATUS __cdecl XOSA_PLUGIN_TenLiraUninit (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	TENLIRA_STATUS*  returnValue);
XOSA_PLUGIN_TenLira_API XOSA_STATUS __cdecl XOSA_PLUGIN_TenLiraInit (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	TENLIRA_STATUS*  returnValue);
XOSA_PLUGIN_TenLira_API XOSA_STATUS __cdecl XOSA_PLUGIN_TenLiraReadFlashByte (
	struct XosaClientConnection * conn, const struct XosaClientApiCallParameters *params,
	char* route_string, uint8_t offset, uint8_t* value, TENLIRA_STATUS*  returnValue);

#ifdef __cplusplus
}
#endif

#endif